name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "VITE_API_URL=https://welcometonextyou.me" > .env

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/AdminDashboardNextYou-
            git remote set-url origin https://Chaouki-BM:${{ secrets.GH_TOKEN }}@github.com/Chaouki-BM/AdminDashboardNextYou-.git
            git pull origin main
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx
